<!-- GTM Data Layer -->
<script>
    if (typeof dataLayer !== 'undefined') {
        <?php echo $block->getChildHtml() ?>
    }
</script>
<script>
    require([
        'Space48Tracking'
    ], function(tracking){

        var customerSession = tracking.getCookie("customerSession");

        if (customerSession !== null && typeof dataLayer !== 'undefined') {
            customerSession = tracking.parseJson(customerSession);
            dataLayer.push(customerSession);
            tracking.delCookie("customerSession");
        }
    });
</script>
<!-- End GTM Data Layer -->
