<!-- GTM Data Layer -->
<script>
    <?php echo $block->getChildHtml() ?>
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Space48Tracking": {}
    }
}
</script>
<script>
    require([
        'Space48_GtmDataLayer/js/tracking'
    ], function(tracking){

        var customerSession = tracking.getCookie("customerSession");

        if (customerSession !== null) {
            customerSession = tracking.parseJson(customerSession);
            dataLayer.push(customerSession);
            tracking.delCookie("customerSession");
        }
    });
</script>
<!-- End GTM Data Layer -->


